Server:
  Port: 8090
ENV: "dev"
JWTKey: "GENERAT-YOUR-JWT-KEY"
Ldap:
  HOST: LDAP-SERVER-ADDRESS
  PORT: LDAP-SERVER-PORT (default is 389)
  USER: LDAP-SERVER-USERNAME
  PASSWORD: LDA-SERVER-PASSWORD 
  BASE: OU=YPUR-OU,DC=EXAMPEL-DOMAIN,DC=local

